### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [MurrayEfford/secrlinear#1]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023.

`secrlinear` imports 'maptools', 'rgdal' using `rgdal::readOGR` as found by `pkgapi`, NAMESPACE also has `importFrom (maptools, spRbind)`, `rgdal::readOGR` in R/read.linearmask.R could be replaced by `sf::st_read` and coerced to `sp`. `spRbind` in R/methods.R could be replaced by `sp:rbind`. `rgeos` is suggested and used in R/clipmask.R, see https://github.com/r-spatial/evolution/blob/main/pkgapi_230305_refs.csv for `sf` equivalents. Moving to `sf` completely might make sense, but probably coercing to and from `sf` may be easier to adapt to packages being retired quickly. Be aware that `rgeos` treated all geometries as planar, `sf` treats spherical geometries as spherical (especially `gBuffer` and `gIntersection`) unless told not to: `sf::sf_use_s2(FALSE)`. Please fix best by June, latest October 2023.

**Comment by MurrayEfford** [comment]
Thanks for the heads up. I had already made the necessary changes in the GitHub version. Now I just need to finalise other changes in version 1.2.0 and send to CRAN. Easily done by June.
